//app.js
import { commonModel } from "./models/common.js"
const common = new commonModel()
App({
  onLaunch: function (options) {
    console.log(options)
   let jsonstr= {
    "platform":[
        {
            "name":"不限",
            "id":0
        },
        {
            "name":"抖音",
            "id":1
        },
        {
            "name":"快手",
            "id":2
        }
    ],
    "list_Tab1":[
        {
            "title":"全部",
            "iden":"All",
            "index":0
        },
        {
            "title":"抖音",
            "iden":"douyin",
            "index":1
        },
        {
            "title":"快手",
            "iden":"kuaishou",
            "index":2
        }
    ],
    "listSelectTab":[
        {
            "platform":"账号类型",
            "type":[
                {
                    "name":"不限",
                    "index":0
                },
                {
                    "name":"穿搭",
                    "index":1
                },
                {
                    "name":"美女",
                    "index":2
                },
                {
                    "name":"搞笑",
                    "index":3
                },
                {
                    "name":"音乐",
                    "index":4
                },
                {
                    "name":"明星",
                    "index":5
                },
                {
                    "name":"影视",
                    "index":6
                },
                {
                    "name":"励志",
                    "index":7
                },
                {
                    "name":"动漫",
                    "index":8
                },
                {
                    "name":"情感",
                    "index":9
                },
                {
                    "name":"玩具",
                    "index":10
                },
                {
                    "name":"母婴",
                    "index":11
                },
                {
                    "name":"游戏",
                    "index":12
                },
                {
                    "name":"美食",
                    "index":13
                },
                {
                    "name":"美妆",
                    "index":14
                },
                {
                    "name":"家居",
                    "index":15
                },
                {
                    "name":"运动",
                    "index":16
                },
                {
                    "name":"个人IP",
                    "index":17
                },
                {
                    "name":"数码",
                    "index":18
                },
                {
                    "name":"宠萌",
                    "index":19
                }
            ]
        },
        {
            "platform":"播放量",
            "type":[
                {
                    "name":"不限",
                    "index":0,
                    "number":"0"
                },
                {
                    "name":"1w以下",
                    "index":1,
                    "number":"<10000"
                },
                {
                    "name":"1-5w",
                    "index":2,
                    "number":"10000-50000"
                },
                {
                    "name":"5-10w",
                    "index":3,
                    "number":"50000-100000"
                },
                {
                    "name":"10-20w",
                    "index":4,
                    "number":"100000-200000"
                },
                {
                    "name":"20-50w",
                    "index":5,
                    "number":"200000-500000"
                },
                {
                    "name":"50-100w",
                    "index":6,
                    "number":"500000-1000000"
                },
                {
                    "name":"100w以上",
                    "index":7,
                    "number":">1000000"
                }
            ]
        },
        {
            "platform":"粉丝量",
            "type":[
                {
                    "name":"不限",
                    "index":0,
                    "number":"0"
                },
                {
                    "name":"千粉",
                    "index":1,
                    "number":"<1000"
                },
                {
                    "name":"3-5k",
                    "index":2,
                    "number":"3000-5000"
                },
                {
                    "name":"5k-1w",
                    "index":3,
                    "number":"<10000"
                },
                {
                    "name":"1-5w",
                    "index":4,
                    "number":"10000-50000"
                },
                {
                    "name":"5-10w",
                    "index":5,
                    "number":"50000-100000"
                },
                {
                    "name":"10-20w",
                    "index":6,
                    "number":"100000-200000"
                },
                {
                    "name":"20-50w",
                    "index":7,
                    "number":"200000-500000"
                },
                {
                    "name":"50-100w",
                    "index":8,
                    "number":"500000-1000000"
                },
                {
                    "name":"100w以上",
                    "index":9,
                    "number":">1000000"
                }
            ]
        },
        {
            "platform":"粉丝属性",
            "type":[
                {
                    "name":"不限",
                    "index":0,
                    "number":"0"
                },
                {
                    "name":"年轻女性",
                    "index":1,
                    "number":"小于23岁"
                },
                {
                    "name":"年轻男性",
                    "index":2,
                    "number":"小于23岁"
                },
                {
                    "name":"青年女性",
                    "index":3,
                    "number":"24-30岁"
                },
                {
                    "name":"青年男性",
                    "index":4,
                    "number":"24-30岁"
                },
                {
                    "name":"中年女性",
                    "index":5,
                    "number":"31-40岁"
                },
                {
                    "name":"中年男性",
                    "index":6,
                    "number":"31-40岁"
                },
                {
                    "name":"中老年女性",
                    "index":7,
                    "number":"41-50岁"
                },
                {
                    "name":"中老年男性",
                    "index":8,
                    "number":"41-50岁"
                },
                {
                    "name":"老年女性",
                    "index":9,
                    "number":"50岁以上"
                },
                {
                    "name":"老年男性",
                    "index":10,
                    "number":"50岁以上"
                }
            ]
        },{
            "platform":"橱窗",
            "type":[
                {
                    "name":"不限",
                    "index":0,
                    "number":"0"
                },{
                    "name":"否",
                    "index":1,
                    "number":"0"
                },
                {
                    "name":"是",
                    "index":2,
                    "number":""
                }
            ]
        },{
            "platform":"实名",
            "type":[
                {
                    "name":"不限",
                    "index":0,
                    "number":"0"
                },{
                    "name":"否",
                    "index":1,
                    "number":"0"
                },
                {
                    "name":"是",
                    "index":2,
                    "number":""
                }
            ]
        },{
            "platform":"蓝V号",
            "type":[
                
                {
                    "name":"不限",
                    "index":0,
                    "number":"0"
                },{
                    "name":"否",
                    "index":1,
                    "number":"1"
                },
                {
                    "name":"是",
                    "index":2,
                    "number":"2"
                }
            ]
        }
    ],
    "violation":[{
        "name":"否",
        "index":0,
        "number":""
    },{
        "name":"是",
        "index":1,
        "number":""
    }],
    "guild":[{
        "name":"未加入",
        "index":0,
        "number":""
    },{
        "name":"已加入",
        "index":1,
        "number":""
    }],
    "storeArr":[{
        "name":"未开通",
        "index":0,
        "number":""
    },{
        "name":"已开通",
        "index":1,
        "number":""
    }],  //居家  美食  女装  美妆  男装  鞋包  数码  配饰  家电  母婴 车品  宠物  其他
    "commodity":[{
        "name":"不限",
        "index":0,
        "number":""
    },{
        "name":"居家",
        "index":1,
        "number":""
    },{
        "name":"美食",
        "index":2,
        "number":""
    },{
        "name":"女装",
        "index":3,
        "number":""
    },{
        "name":"美妆",
        "index":4,
        "number":""
    },{
        "name":"男装",
        "index":5,
        "number":""
    },{
        "name":"鞋包",
        "index":6,
        "number":""
    },{
        "name":"数码",
        "index":7,
        "number":""
    },{
        "name":"配饰",
        "index":8,
        "number":""
    },{
        "name":"家电",
        "index":9,
        "number":""
    },{
        "name":"母婴",
        "index":10,
        "number":""
    },{
        "name":"车品",
        "index":11,
        "number":""
    },{
        "name":"宠物",
        "index":12,
        "number":""
    },{
        "name":"其他",
        "index":13,
        "number":""
    }],
    "needFandsType":[
        {//'1000粉橱窗号','1000粉三五','三千分三无','三千分橱窗','千粉撸过的号','万粉橱窗号','万粉三无号','万粉撸过的号','万粉评级号','万粉违规号','蓝V白号','蓝V千粉三无号','蓝V千粉橱窗号','垂直号','自定义需求'
            "name":"不限",
            "index":0
        },{"name":"1000粉橱窗号","index":0},
        {"name":"1000粉三五","index":1},
        {"name":"三千分三无","index":2},
        {"name":"三千分橱窗","index":3},
        {"name":"千粉撸过的号","index":4},
        {"name":"万粉橱窗号","index":5},
        {"name":"万粉三无号","index":6},
        {"name":"万粉撸过的号","index":7},
        {"name":"万粉评级号","index":8},
        {"name":"万粉违规号","index":9},
        {"name":"蓝V白号","index":10},
        {"name":"蓝V千粉三无号","index":11},
        {"name":"蓝V千粉橱窗号","index":12},
        {"name":"垂直号","index":13},
        {"name":"自定义需求","index":14}
    ],
    "commissionRate":[
        {"name":"10%","index":0,"number":10},
        {"name":"20%","index":1,"number":20},
        {"name":"30%","index":2,"number":30},
        {"name":"40%","index":3,"number":40},
        {"name":"50%","index":4,"number":50},
    ],
    "commissionType":[
        {"name":"定向","index":0},
        {"name":"通用","index":1}
    ],
    "isSamples":[
        {"name":"有","index":0},
        {"name":"无","index":1}
    ]
}
  this.globalData.gse=jsonstr
    // 判断是否由分享进入小程序
    if (options.scene == 1007 || options.scene == 1008) {
      this.globalData.share = true
    } else {
      this.globalData.share = false
    };
    
    //获取设备顶部窗口的高度
    wx.getSystemInfo({
      success: (res) => {
        if (res.model == 'iPhone X'){
          this.globalData.height = 30
          console.log(res.brand)
          console.log(res.model)
          console.log(res.statusBarHeight)
        }else{
          this.globalData.height = res.statusBarHeight
        }
        
      }
    })
    //获取用户权限
    common.userAuth().then(res => {
      wx.setStorageSync('userAuth', res)
      if(res.user_limit == 3){
        wx.reLaunch({
          url: '/pages/limit-msg/index'
        })
      }
      
    })
    // wx.loadFontFace({
    //   family: 'webfont',
    //   source: 'url("https://w7.hey1.net/addons/hey1_demo/core/public/wxapp/font-family.ttf")',
    //   success: console.log
    // })
    /*1=图文:2=视频;3=快手;4=抖音
      sub_type:
      3=出售快手,4=出售抖音,5=发布商品
      11=发布收号需求， 12= 发布其他需求
      21=抖音新动态，22=快手新动态，23=最新玩法，24=掘金抖音，25=掘金快手
    */
  },
  globalData: {
    share: false,  // 分享默认为false
    height: 0,
    gse:[]
  },
  siteInfo: require('siteinfo.js'),
  returnNumber(data)
  {
    for(var i=0; i<data.length; i++)
      {
        if (data[i].playNum != '' && !isNaN(data[i].playNum))
        {
          if(data[i].playNum <= 9999)
          {
            data[i].playNum=(data[i].playNum/1000).toFixed(1)+"K"
          }else
          {
            data[i].playNum=(data[i].playNum/10000).toFixed(1)+"W"
          }
        }

        if (data[i].fandsNum != '' && !isNaN(data[i].fandsNum))
        {
          if(data[i].fandsNum <= 9999)
          {
            data[i].fandsNum=(data[i].fandsNum/1000).toFixed(1)+"K"
          }else
          {
            data[i].fandsNum=(data[i].fandsNum/10000).toFixed(1)+"W"
          }
        }
      }
      return data;
  }
})